using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by FA2CS (https://github.com/matthewrdev/fa2cs).
    /// </summary>
    /// 
    public static partial class FontAwesomeIcons
    {
        public static string Arrow_Alt_Circle_Down = "\uf358";
        public static string Arrow_Alt_Circle_Left = "\uf359";
        public static string Arrow_Alt_Circle_Right = "\uf35a";
        public static string Arrow_Alt_Circle_Up = "\uf35b";
        public static string Arrow_Circle_Down = "\uf0ab";
        public static string Arrow_Circle_Left = "\uf0a8";
        public static string Arrow_Circle_Right = "\uf0a9";
        public static string Arrow_Circle_Up = "\uf0aa";
        public static string Arrow_Down = "\uf063";
        public static string Arrow_Left = "\uf060";
        public static string Arrow_Right = "\uf061";
        public static string Arrow_Up = "\uf062";
        public static string Arrows_Alt = "\uf0b2";
        public static string Arrows_Alt_H = "\uf337";
        public static string Arrows_Alt_V = "\uf338";
        public static string Add_icon = "\uf067";
        public static string Add_Sync_alt = "\uf2f1";
        public static string link = "\uf0c1";
        public static string unlink = "\uf127";
        public static string chevron_right = "\uf054";
        public static string chevron_left = "\uf053";
        public static string user_clock = "\uf4fd";
        public static string ellipsis_v = "\uf142";
        public static string list_ul = "\uf0ca";





        // Used
        public static string Sign_Out_Alt = "\uf2f5";
        public static string Cog = "\uf013";
        public static string Filter = "\uf0b0";
        public static string Home = "\uf015";
        public static string Sell = "\uf290";
        public static string MoneyTransaction = "\uf3d1";
        public static string About = "\uf05a";
        public static string Session = "\uf0c0";
        public static string Tresorerie = "\uf4c0";
        public static string Shopping_basket = "\uf291";
        public static string Pills = "\uf484";
        public static string File_invoice_dollar = "\uf571";
        public static string Box_alt = "\uf49a";
        public static string Handshake = "\uf2b5";
        public static string Poll = "\uf681";
        public static string Poll_h = "\uf682";
        public static string Shipping_timed = "\uf48b";
        public static string Money_check_edit_alt = "\uf873";
        public static string Sort_size_up_alt = "\uf88f";
        public static string Hand_holding_box = "\uf47b";
        public static string Newspaper = "\uf1ea";
        public static string Store_alt = "\uf54f";
        public static string Clipboard_list_check = "\uf737";
        public static string box_check = "\uf467";
        public static string chart_line = "\uf201";
        public static string User_edit = "\uf4ff";


        /// <summary>
        /// fa-cart-arrow-down unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/cart-arrow-down
        /// </summary>
        public const string CartArrowDown = "\uf218";


        /// <summary>
        /// fa-list-ul unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/list-ul
        /// </summary>
        public const string ListUl = "\uf0ca";

        /// <summary>
        /// fa-th unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/th
        /// </summary>
        public const string Th = "\uf00a";

        /// <summary>
        /// fa-th-large unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/th-large
        /// </summary>
        public const string ThLarge = "\uf009";

        /// <summary>
        /// fa-ellipsis-v unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/ellipsis-v
        /// </summary>
        public const string EllipsisV = "\uf142";

        /// <summary>
        /// fa-door-open unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/door-open
        /// </summary>
        public const string DoorOpen = "\uf52b";

        /// <summary>
        /// fa-file-chart-line unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/file-chart-line
        /// </summary>
        public const string FileChartLine = "\uf659";

        /// <summary>
        /// fa-boxes unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/boxes
        /// </summary>
        public const string Boxes = "\uf468";

        /// <summary>
        /// fa-barcode unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/barcode
        /// </summary>
        public const string Barcode = "\uf02a";

        /// <summary>
        /// fa-arrow-left unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/arrow-left
        /// </summary>
        public const string ArrowLeft = "\uf060";

        /// <summary>
        /// fa-trash-alt unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid
        /// <para/>
        /// See https://fontawesome.com/icons/trash-alt
        /// </summary>
        public const string TrashAlt = "\uf2ed";


        /// <summary>
        /// fa-search unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/search
        /// </summary>
        public const string Search = "\uf002";

        /// <summary>
        /// fa-cube unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/cube
        /// </summary>
        public const string Cube = "\uf1b2";

        /// <summary>
        /// fa-money-bill-wave unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/money-bill-wave
        /// </summary>
        public const string MoneyBillWave = "\uf53a";

        /// <summary>
        /// fa-calendar-alt unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid
        /// <para/>
        /// See https://fontawesome.com/icons/calendar-alt
        /// </summary>
        public const string CalendarAlt = "\uf073";

        /// <summary>
        /// fa-exchange-alt unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/exchange-alt
        /// </summary>
        public const string ExchangeAlt = "\uf362";

        /// <summary>
        /// fa-info unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/info
        /// </summary>
        public const string Info = "\uf129";

        /// <summary>
        /// fa-info-circle unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/info-circle
        /// </summary>
        public const string InfoCircle = "\uf05a";

        /// <summary>
        /// fa-sync unicode value.
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular (Pro), Solid
        /// <para/>
        /// See https://fontawesome.com/icons/sync
        /// </summary>
        public const string Sync = "\uf021";

        /// <summary>
        /// fa-save unicode value ("\uf0c7").
        /// <para/>
        /// This icon supports the following styles: Light (Pro), Regular, Solid, Duotone (Pro)
        /// <para/>
        /// See https://fontawesome.com/icons/save
        /// </summary>
        public const string Save = "\uf0c7";

        public const string print = "\uf02f";
        public const string usercircle = "\uf2bd";
        public const string users = "\uf0c0";
        public const string faBars = "\uf0c9";

        public const string sortAlphaDown = "\uf15d";

    }
}