//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XpertMobileApp {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XpertMobileApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à , elle vous permet d&apos;accéder a vos informations rapidement là ou vous soyez.
        /// </summary>
        internal static string abtp_lbl_AppDescription {
            get {
                return ResourceManager.GetString("abtp_lbl_AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Application développé  par .
        /// </summary>
        internal static string abtp_lbl_DevelopedBy {
            get {
                return ResourceManager.GetString("abtp_lbl_DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En savoir plus ...
        /// </summary>
        internal static string abtp_lbl_LearnMore {
            get {
                return ResourceManager.GetString("abtp_lbl_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;une des Tags scannée est déjà affectées a un lots !.
        /// </summary>
        internal static string Alert_Deplicatrd_Rfid_Tages {
            get {
                return ResourceManager.GetString("Alert_Deplicatrd_Rfid_Tages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;initialisation du lecteur RFID a échoué!.
        /// </summary>
        internal static string Alrt_failInitRFID_Reader {
            get {
                return ResourceManager.GetString("Alrt_failInitRFID_Reader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alerte.
        /// </summary>
        internal static string alrt_msg_Alert {
            get {
                return ResourceManager.GetString("alrt_msg_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string alrt_msg_Cancel {
            get {
                return ResourceManager.GetString("alrt_msg_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur lors de la tentative de connexion.
        /// </summary>
        internal static string alrt_msg_CantTestConnexionSettings {
            get {
                return ResourceManager.GetString("alrt_msg_CantTestConnexionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Si vous désactivé votre licence vous ne pourrez plus l&apos;utiliser jusqu&apos;a sa reactivation, voulez vous continuer ?.
        /// </summary>
        internal static string alrt_msg_CondifirmDesactivateLicence {
            get {
                return ResourceManager.GetString("alrt_msg_CondifirmDesactivateLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion échoué veullez vérifier les informations du serveur.
        /// </summary>
        internal static string alrt_msg_ConnectionError {
            get {
                return ResourceManager.GetString("alrt_msg_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion établie avec succes.
        /// </summary>
        internal static string alrt_msg_ConnectionSucces {
            get {
                return ResourceManager.GetString("alrt_msg_ConnectionSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos.
        /// </summary>
        internal static string alrt_msg_Info {
            get {
                return ResourceManager.GetString("alrt_msg_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez autoriser l&apos;application a accéder aux informations de votre appareil pour pouvoir vous identifier et vous permettre d&apos;activer votre licence..
        /// </summary>
        internal static string alrt_msg_MissingDeviceInfos {
            get {
                return ResourceManager.GetString("alrt_msg_MissingDeviceInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez renseigner les informations du serveur.
        /// </summary>
        internal static string alrt_msg_MissingServerInfos {
            get {
                return ResourceManager.GetString("alrt_msg_MissingServerInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il y a plusieurs lots pour ce code à barres !.
        /// </summary>
        internal static string alrt_msg_multiLotForCodeBarre {
            get {
                return ResourceManager.GetString("alrt_msg_multiLotForCodeBarre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas de lot correspondants a ce code à barre !.
        /// </summary>
        internal static string alrt_msg_NotFondLotFromCodeBarre {
            get {
                return ResourceManager.GetString("alrt_msg_NotFondLotFromCodeBarre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        internal static string alrt_msg_Ok {
            get {
                return ResourceManager.GetString("alrt_msg_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous enregistrer la configuration.
        /// </summary>
        internal static string alrt_msg_SaveSettings {
            get {
                return ResourceManager.GetString("alrt_msg_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La configuration a été enregistrées avec succès.
        /// </summary>
        internal static string alrt_msg_SettingsSaved {
            get {
                return ResourceManager.GetString("alrt_msg_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration.
        /// </summary>
        internal static string alrt_msg_title_Settings {
            get {
                return ResourceManager.GetString("alrt_msg_title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pas d&apos;inventaire ouvert !.
        /// </summary>
        internal static string alrt_notOpenInventary_Text {
            get {
                return ResourceManager.GetString("alrt_notOpenInventary_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour.
        /// </summary>
        internal static string app_speech_Hello {
            get {
                return ResourceManager.GetString("app_speech_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Effacer.
        /// </summary>
        internal static string btn_Clear_Text {
            get {
                return ResourceManager.GetString("btn_Clear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string btn_Close {
            get {
                return ResourceManager.GetString("btn_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Config.
        /// </summary>
        internal static string btn_Filter_RFID_Text {
            get {
                return ResourceManager.GetString("btn_Filter_RFID_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Balayage.
        /// </summary>
        internal static string btn_scan_Rfid_Text {
            get {
                return ResourceManager.GetString("btn_scan_Rfid_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scanner Code à barre.
        /// </summary>
        internal static string btn_scanCodeBarre {
            get {
                return ResourceManager.GetString("btn_scanCodeBarre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arréter.
        /// </summary>
        internal static string btn_Stop_Scan_Rfid {
            get {
                return ResourceManager.GetString("btn_Stop_Scan_Rfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Traitement.
        /// </summary>
        internal static string btn_Trait_Rfids_text {
            get {
                return ResourceManager.GetString("btn_Trait_Rfids_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        internal static string cmd_Add {
            get {
                return ResourceManager.GetString("cmd_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        internal static string cmd_Cancel {
            get {
                return ResourceManager.GetString("cmd_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        internal static string cmd_Delete {
            get {
                return ResourceManager.GetString("cmd_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        internal static string cmd_Disconnect {
            get {
                return ResourceManager.GetString("cmd_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtre.
        /// </summary>
        internal static string cmd_Filter {
            get {
                return ResourceManager.GetString("cmd_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enlever.
        /// </summary>
        internal static string cmd_remove {
            get {
                return ResourceManager.GetString("cmd_remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        internal static string cmd_Save {
            get {
                return ResourceManager.GetString("cmd_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chercher.
        /// </summary>
        internal static string cmd_seach {
            get {
                return ResourceManager.GetString("cmd_seach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner.
        /// </summary>
        internal static string cmd_SelectElement {
            get {
                return ResourceManager.GetString("cmd_SelectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier.
        /// </summary>
        internal static string cmd_Update {
            get {
                return ResourceManager.GetString("cmd_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vérification.
        /// </summary>
        internal static string cmd_Verif {
            get {
                return ResourceManager.GetString("cmd_Verif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte.
        /// </summary>
        internal static string CODE_COMPTE {
            get {
                return ResourceManager.GetString("CODE_COMPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motif.
        /// </summary>
        internal static string CODE_MOTIF {
            get {
                return ResourceManager.GetString("CODE_MOTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tiers.
        /// </summary>
        internal static string CODE_TIERS {
            get {
                return ResourceManager.GetString("CODE_TIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à XpertSoft.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string DATE_ENCAISS {
            get {
                return ResourceManager.GetString("DATE_ENCAISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte.
        /// </summary>
        internal static string DESIGN_COMPTE {
            get {
                return ResourceManager.GetString("DESIGN_COMPTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Motif.
        /// </summary>
        internal static string DESIGN_MOTIF {
            get {
                return ResourceManager.GetString("DESIGN_MOTIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;url de connexion est incorrecte.
        /// </summary>
        internal static string err_msg_badConnexionUrl {
            get {
                return ResourceManager.GetString("err_msg_badConnexionUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez vérifier les informations d&apos;authentification.
        /// </summary>
        internal static string err_msg_IncorrectLoginInfos {
            get {
                return ResourceManager.GetString("err_msg_IncorrectLoginInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur de chargement de données.
        /// </summary>
        internal static string err_msg_loadingDataError {
            get {
                return ResourceManager.GetString("err_msg_loadingDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner un compte.
        /// </summary>
        internal static string error_AccountNotEmpty {
            get {
                return ResourceManager.GetString("error_AccountNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez corriger la date d&apos;échéance.
        /// </summary>
        internal static string error_DateShouldBeGreaterThanToday {
            get {
                return ResourceManager.GetString("error_DateShouldBeGreaterThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner un tiers.
        /// </summary>
        internal static string error_ThirdNotEmpty {
            get {
                return ResourceManager.GetString("error_ThirdNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;option demandé n&apos;est pas disponible dans votre licence.
        /// </summary>
        internal static string Exception_errMsg_20 {
            get {
                return ResourceManager.GetString("Exception_errMsg_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client avec produit concerné non existant.
        /// </summary>
        internal static string Exception_errMsg_21 {
            get {
                return ResourceManager.GetString("Exception_errMsg_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nombre de licences expiré.
        /// </summary>
        internal static string Exception_errMsg_22 {
            get {
                return ResourceManager.GetString("Exception_errMsg_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes déjà enregistré.
        /// </summary>
        internal static string Exception_errMsg_23 {
            get {
                return ResourceManager.GetString("Exception_errMsg_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre licence a déjà été désactivé!.
        /// </summary>
        internal static string Exception_errMsg_31 {
            get {
                return ResourceManager.GetString("Exception_errMsg_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous n&apos;avons pas pu trouver votre licence!.
        /// </summary>
        internal static string Exception_errMsg_32 {
            get {
                return ResourceManager.GetString("Exception_errMsg_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette licence est généré pour un autre appareil.
        /// </summary>
        internal static string InvalidDevice {
            get {
                return ResourceManager.GetString("InvalidDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Continue.
        /// </summary>
        internal static string lbl_Continues_scan_RFID {
            get {
                return ResourceManager.GetString("lbl_Continues_scan_RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date :.
        /// </summary>
        internal static string lbl_DateInventqire_Text {
            get {
                return ResourceManager.GetString("lbl_DateInventqire_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lot..
        /// </summary>
        internal static string lbl_lot_txt {
            get {
                return ResourceManager.GetString("lbl_lot_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Num inventaire :.
        /// </summary>
        internal static string lbl_NumInventaire {
            get {
                return ResourceManager.GetString("lbl_NumInventaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activer.
        /// </summary>
        internal static string lp_btn_Activate {
            get {
                return ResourceManager.GetString("lp_btn_Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string lp_btn_Login {
            get {
                return ResourceManager.GetString("lp_btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string lp_btn_Settings {
            get {
                return ResourceManager.GetString("lp_btn_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant client.
        /// </summary>
        internal static string lp_lbl_ClientId {
            get {
                return ResourceManager.GetString("lp_lbl_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string lp_lbl_PassWord {
            get {
                return ResourceManager.GetString("lp_lbl_PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string lp_lbl_UserEemail {
            get {
                return ResourceManager.GetString("lp_lbl_UserEemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        internal static string lp_lbl_UserName {
            get {
                return ResourceManager.GetString("lp_lbl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        internal static string lp_lbl_UserPhone {
            get {
                return ResourceManager.GetString("lp_lbl_UserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        internal static string lp_Login {
            get {
                return ResourceManager.GetString("lp_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur ou mot de passe incorrect!.
        /// </summary>
        internal static string lp_login_WrongAcces {
            get {
                return ResourceManager.GetString("lp_login_WrongAcces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifiant client.
        /// </summary>
        internal static string lp_ph_ClientId {
            get {
                return ResourceManager.GetString("lp_ph_ClientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string lp_ph_PassWord {
            get {
                return ResourceManager.GetString("lp_ph_PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        internal static string lp_ph_UserEemail {
            get {
                return ResourceManager.GetString("lp_ph_UserEemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        internal static string lp_ph_UserName {
            get {
                return ResourceManager.GetString("lp_ph_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        internal static string lp_ph_UserPhone {
            get {
                return ResourceManager.GetString("lp_ph_UserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;activation de votre licence s&apos;est éffectué avec succes, vous pouvez désormais utiliser votre application..
        /// </summary>
        internal static string msg_ActivationSucces {
            get {
                return ResourceManager.GetString("msg_ActivationSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirmation.
        /// </summary>
        internal static string msg_Confirmation {
            get {
                return ResourceManager.GetString("msg_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La désactivation de votre licence s&apos;est déroulé avec succes..
        /// </summary>
        internal static string msg_DeactivationSucces {
            get {
                return ResourceManager.GetString("msg_DeactivationSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez-vous vraiment supprimer cet élément ?.
        /// </summary>
        internal static string msg_DeleteConfirmation {
            get {
                return ResourceManager.GetString("msg_DeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrer le montant s&apos;il vous plaît .
        /// </summary>
        internal static string msg_EnterTheAmount {
            get {
                return ResourceManager.GetString("msg_EnterTheAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Expire le.
        /// </summary>
        internal static string msg_ExpireOn {
            get {
                return ResourceManager.GetString("msg_ExpireOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous utilisez une licence crackée.
        /// </summary>
        internal static string msg_Licence_Cracked {
            get {
                return ResourceManager.GetString("msg_Licence_Cracked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre licence a expiré, vous devez réactiver votre application.
        /// </summary>
        internal static string msg_Licence_Expired {
            get {
                return ResourceManager.GetString("msg_Licence_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre application n&apos;est pas encore activée, veuillez procéder a son activation..
        /// </summary>
        internal static string msg_Licence_NotActivated {
            get {
                return ResourceManager.GetString("msg_Licence_NotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tiers.
        /// </summary>
        internal static string NOM_TIERS {
            get {
                return ResourceManager.GetString("NOM_TIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pesée d&apos;entrée.
        /// </summary>
        internal static string PESEE_ENTREE {
            get {
                return ResourceManager.GetString("PESEE_ENTREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pesée de sortie.
        /// </summary>
        internal static string PESEE_SORTIE {
            get {
                return ResourceManager.GetString("PESEE_SORTIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher .....
        /// </summary>
        internal static string ph_seachedtxt {
            get {
                return ResourceManager.GetString("ph_seachedtxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos.
        /// </summary>
        internal static string pn_About {
            get {
                return ResourceManager.GetString("pn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Liste des pesées.
        /// </summary>
        internal static string pn_Achats {
            get {
                return ResourceManager.GetString("pn_Achats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réception pour production.
        /// </summary>
        internal static string pn_AchatsProduction {
            get {
                return ResourceManager.GetString("pn_AchatsProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activation.
        /// </summary>
        internal static string pn_Activation {
            get {
                return ResourceManager.GetString("pn_Activation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyses.
        /// </summary>
        internal static string pn_Analyses {
            get {
                return ResourceManager.GetString("pn_Analyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bordereaux.
        /// </summary>
        internal static string pn_Bordereaux {
            get {
                return ResourceManager.GetString("pn_Bordereaux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Catalogue.
        /// </summary>
        internal static string pn_Catalogues {
            get {
                return ResourceManager.GetString("pn_Catalogues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commandes clients.
        /// </summary>
        internal static string pn_Commandes {
            get {
                return ResourceManager.GetString("pn_Commandes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encaiss &amp; Décaiss.
        /// </summary>
        internal static string pn_encaissement {
            get {
                return ResourceManager.GetString("pn_encaissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        internal static string pn_home {
            get {
                return ResourceManager.GetString("pn_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentification.
        /// </summary>
        internal static string pn_Login {
            get {
                return ResourceManager.GetString("pn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manquants.
        /// </summary>
        internal static string pn_Manquants {
            get {
                return ResourceManager.GetString("pn_Manquants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes commandes.
        /// </summary>
        internal static string pn_MyCommandes {
            get {
                return ResourceManager.GetString("pn_MyCommandes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle commande.
        /// </summary>
        internal static string pn_NewCommande {
            get {
                return ResourceManager.GetString("pn_NewCommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle pesée.
        /// </summary>
        internal static string pn_NewPurchase {
            get {
                return ResourceManager.GetString("pn_NewPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelle pesée.
        /// </summary>
        internal static string pn_NewReception {
            get {
                return ResourceManager.GetString("pn_NewReception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ordres de production.
        /// </summary>
        internal static string pn_OrdresProduction {
            get {
                return ResourceManager.GetString("pn_OrdresProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produits.
        /// </summary>
        internal static string pn_Produits {
            get {
                return ResourceManager.GetString("pn_Produits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inventaire RFID.
        /// </summary>
        internal static string pn_rfid_inventaire {
            get {
                return ResourceManager.GetString("pn_rfid_inventaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rfid scan.
        /// </summary>
        internal static string pn_RfidScan {
            get {
                return ResourceManager.GetString("pn_RfidScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sessions.
        /// </summary>
        internal static string pn_session {
            get {
                return ResourceManager.GetString("pn_session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tiers.
        /// </summary>
        internal static string pn_Tiers {
            get {
                return ResourceManager.GetString("pn_Tiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trésorerie.
        /// </summary>
        internal static string pn_Tresorerie {
            get {
                return ResourceManager.GetString("pn_Tresorerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ventes.
        /// </summary>
        internal static string pn_Ventes {
            get {
                return ResourceManager.GetString("pn_Ventes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ventes psychotropes.
        /// </summary>
        internal static string pn_VtePsychotrop {
            get {
                return ResourceManager.GetString("pn_VtePsychotrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qte Produite.
        /// </summary>
        internal static string QTE_PRODUITE {
            get {
                return ResourceManager.GetString("QTE_PRODUITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Solde tiers.
        /// </summary>
        internal static string SOLDE_TIERS {
            get {
                return ResourceManager.GetString("SOLDE_TIERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désactiver la licence.
        /// </summary>
        internal static string sp_btn_RemoveLicence {
            get {
                return ResourceManager.GetString("sp_btn_RemoveLicence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        internal static string sp_btn_SaveRfid {
            get {
                return ResourceManager.GetString("sp_btn_SaveRfid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        internal static string sp_btn_SaveSettings {
            get {
                return ResourceManager.GetString("sp_btn_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tester la connexion.
        /// </summary>
        internal static string sp_btn_TestConnection {
            get {
                return ResourceManager.GetString("sp_btn_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations de connexion.
        /// </summary>
        internal static string sp_lbl_ConnexionInfos {
            get {
                return ResourceManager.GetString("sp_lbl_ConnexionInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information sur la licence.
        /// </summary>
        internal static string sp_lbl_LicenceInfos {
            get {
                return ResourceManager.GetString("sp_lbl_LicenceInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        internal static string sp_lbl_PortNumber {
            get {
                return ResourceManager.GetString("sp_lbl_PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langage.
        /// </summary>
        internal static string sp_lbl_SelectLanguage {
            get {
                return ResourceManager.GetString("sp_lbl_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serveur.
        /// </summary>
        internal static string sp_lbl_ServerName {
            get {
                return ResourceManager.GetString("sp_lbl_ServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Url du service.
        /// </summary>
        internal static string sp_lbl_ServiceName {
            get {
                return ResourceManager.GetString("sp_lbl_ServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string tct_Type {
            get {
                return ResourceManager.GetString("tct_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total encaissé.
        /// </summary>
        internal static string TOTAL_ENCAISS {
            get {
                return ResourceManager.GetString("TOTAL_ENCAISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A Cmdé.
        /// </summary>
        internal static string txt_Acommande {
            get {
                return ResourceManager.GetString("txt_Acommande", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix :.
        /// </summary>
        internal static string txt_agri_Prix {
            get {
                return ResourceManager.GetString("txt_agri_Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Q.Brute :.
        /// </summary>
        internal static string txt_agri_QBrute {
            get {
                return ResourceManager.GetString("txt_agri_QBrute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Q.Déchet :.
        /// </summary>
        internal static string txt_agri_QDechet {
            get {
                return ResourceManager.GetString("txt_agri_QDechet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Q.Net :.
        /// </summary>
        internal static string txt_agri_QNet {
            get {
                return ResourceManager.GetString("txt_agri_QNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déchet % :.
        /// </summary>
        internal static string txt_agri_TauxDechet {
            get {
                return ResourceManager.GetString("txt_agri_TauxDechet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tous.
        /// </summary>
        internal static string txt_All {
            get {
                return ResourceManager.GetString("txt_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Arrivage.
        /// </summary>
        internal static string txt_Arrivage {
            get {
                return ResourceManager.GetString("txt_Arrivage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter au panier.
        /// </summary>
        internal static string txt_Buy {
            get {
                return ResourceManager.GetString("txt_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chiffre d&apos;affaires.
        /// </summary>
        internal static string txt_CA {
            get {
                return ResourceManager.GetString("txt_CA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre commande a bien été envoyée!.
        /// </summary>
        internal static string txt_Cat_CommandesSaved {
            get {
                return ResourceManager.GetString("txt_Cat_CommandesSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre commande a bien été modifiée!.
        /// </summary>
        internal static string txt_Cat_CommandesUpdated {
            get {
                return ResourceManager.GetString("txt_Cat_CommandesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document enregistré avec succès !
        ///.
        /// </summary>
        internal static string txt_Cat_DocumentSaved {
            get {
                return ResourceManager.GetString("txt_Cat_DocumentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Document modifié avec succès !.
        /// </summary>
        internal static string txt_Cat_DocumentUpdated {
            get {
                return ResourceManager.GetString("txt_Cat_DocumentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Famille.
        /// </summary>
        internal static string txt_Categorie {
            get {
                return ResourceManager.GetString("txt_Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centre.
        /// </summary>
        internal static string txt_Centre {
            get {
                return ResourceManager.GetString("txt_Centre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chauffeur.
        /// </summary>
        internal static string txt_Chauffeur {
            get {
                return ResourceManager.GetString("txt_Chauffeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Client.
        /// </summary>
        internal static string txt_Client {
            get {
                return ResourceManager.GetString("txt_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compte.
        /// </summary>
        internal static string txt_Compte {
            get {
                return ResourceManager.GetString("txt_Compte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Comptes.
        /// </summary>
        internal static string txt_Comptes {
            get {
                return ResourceManager.GetString("txt_Comptes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Voulez vous vraiment supprimer ce produit du panier ?.
        /// </summary>
        internal static string txt_ConfimDelProductCmd {
            get {
                return ResourceManager.GetString("txt_ConfimDelProductCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Couverts.
        /// </summary>
        internal static string txt_CovredDays {
            get {
                return ResourceManager.GetString("txt_CovredDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        internal static string txt_Date {
            get {
                return ResourceManager.GetString("txt_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jour.
        /// </summary>
        internal static string txt_Day {
            get {
                return ResourceManager.GetString("txt_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Décaissement.
        /// </summary>
        internal static string txt_Decaiss {
            get {
                return ResourceManager.GetString("txt_Decaiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Détails.
        /// </summary>
        internal static string txt_Details {
            get {
                return ResourceManager.GetString("txt_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Échéance.
        /// </summary>
        internal static string txt_EcheanceDate {
            get {
                return ResourceManager.GetString("txt_EcheanceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrées.
        /// </summary>
        internal static string txt_EmballageEntree {
            get {
                return ResourceManager.GetString("txt_EmballageEntree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sortie.
        /// </summary>
        internal static string txt_EmballageSortie {
            get {
                return ResourceManager.GetString("txt_EmballageSortie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vides.
        /// </summary>
        internal static string txt_EmballageVides {
            get {
                return ResourceManager.GetString("txt_EmballageVides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encaissement.
        /// </summary>
        internal static string txt_Encaiss {
            get {
                return ResourceManager.GetString("txt_Encaiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encaissements.
        /// </summary>
        internal static string txt_Encaissments {
            get {
                return ResourceManager.GetString("txt_Encaissments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date fin.
        /// </summary>
        internal static string txt_EndDate {
            get {
                return ResourceManager.GetString("txt_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Famille.
        /// </summary>
        internal static string txt_Famille {
            get {
                return ResourceManager.GetString("txt_Famille", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtrer.
        /// </summary>
        internal static string txt_Filter {
            get {
                return ResourceManager.GetString("txt_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entête.
        /// </summary>
        internal static string txt_header {
            get {
                return ResourceManager.GetString("txt_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matricule.
        /// </summary>
        internal static string txt_Immatriculation {
            get {
                return ResourceManager.GetString("txt_Immatriculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos collectées au cours des 30 derniers jours.
        /// </summary>
        internal static string txt_InfosProdNbrDaysAnalysed {
            get {
                return ResourceManager.GetString("txt_InfosProdNbrDaysAnalysed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ordonnancier.
        /// </summary>
        internal static string txt_InfosPsyco {
            get {
                return ResourceManager.GetString("txt_InfosPsyco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prénom.
        /// </summary>
        internal static string txt_LastName {
            get {
                return ResourceManager.GetString("txt_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chargement ....
        /// </summary>
        internal static string txt_Loading {
            get {
                return ResourceManager.GetString("txt_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lots.
        /// </summary>
        internal static string txt_Lots {
            get {
                return ResourceManager.GetString("txt_Lots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Manquants.
        /// </summary>
        internal static string txt_MANQUANTS {
            get {
                return ResourceManager.GetString("txt_MANQUANTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marges.
        /// </summary>
        internal static string txt_Margin {
            get {
                return ResourceManager.GetString("txt_Margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marges par vendeur.
        /// </summary>
        internal static string txt_MarginsByseller {
            get {
                return ResourceManager.GetString("txt_MarginsByseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Montant clôture.
        /// </summary>
        internal static string txt_Mnt_Cloture {
            get {
                return ResourceManager.GetString("txt_Mnt_Cloture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Crédits.
        /// </summary>
        internal static string txt_Mnt_Credits {
            get {
                return ResourceManager.GetString("txt_Mnt_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ÉCART.
        /// </summary>
        internal static string txt_Mnt_Ecart {
            get {
                return ResourceManager.GetString("txt_Mnt_Ecart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        internal static string txt_Mnt_Retour {
            get {
                return ResourceManager.GetString("txt_Mnt_Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tarif Chifa.
        /// </summary>
        internal static string txt_Mnt_TarifCHIFA {
            get {
                return ResourceManager.GetString("txt_Mnt_TarifCHIFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vente cash.
        /// </summary>
        internal static string txt_Mnt_VenteCash {
            get {
                return ResourceManager.GetString("txt_Mnt_VenteCash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mois.
        /// </summary>
        internal static string txt_Month {
            get {
                return ResourceManager.GetString("txt_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom.
        /// </summary>
        internal static string txt_Name {
            get {
                return ResourceManager.GetString("txt_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveaux.
        /// </summary>
        internal static string txt_NewProduct {
            get {
                return ResourceManager.GetString("txt_NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Téléphone.
        /// </summary>
        internal static string txt_phone {
            get {
                return ResourceManager.GetString("txt_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Prix.
        /// </summary>
        internal static string txt_Prix {
            get {
                return ResourceManager.GetString("txt_Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Produit.
        /// </summary>
        internal static string txt_Product {
            get {
                return ResourceManager.GetString("txt_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Productivité.
        /// </summary>
        internal static string txt_Productivite {
            get {
                return ResourceManager.GetString("txt_Productivite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qté.
        /// </summary>
        internal static string txt_Qte {
            get {
                return ResourceManager.GetString("txt_Qte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vendu.
        /// </summary>
        internal static string txt_QTE_VENTE {
            get {
                return ResourceManager.GetString("txt_QTE_VENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apport.
        /// </summary>
        internal static string txt_QteApport {
            get {
                return ResourceManager.GetString("txt_QteApport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qté Min.
        /// </summary>
        internal static string txt_QteMin {
            get {
                return ResourceManager.GetString("txt_QteMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Qte Produite.
        /// </summary>
        internal static string txt_QteProduite {
            get {
                return ResourceManager.GetString("txt_QteProduite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réf.
        /// </summary>
        internal static string txt_Ref {
            get {
                return ResourceManager.GetString("txt_Ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rotation.
        /// </summary>
        internal static string txt_Rotation {
            get {
                return ResourceManager.GetString("txt_Rotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ventes.
        /// </summary>
        internal static string txt_Sales {
            get {
                return ResourceManager.GetString("txt_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ventes par vendeur.
        /// </summary>
        internal static string txt_SalesBySeller {
            get {
                return ResourceManager.GetString("txt_SalesBySeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scanner.
        /// </summary>
        internal static string txt_ScanRow {
            get {
                return ResourceManager.GetString("txt_ScanRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Recherche.
        /// </summary>
        internal static string txt_Search {
            get {
                return ResourceManager.GetString("txt_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner.
        /// </summary>
        internal static string txt_SelectRow {
            get {
                return ResourceManager.GetString("txt_SelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vendeur.
        /// </summary>
        internal static string txt_Seler {
            get {
                return ResourceManager.GetString("txt_Seler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez procéder a la mise à jour de vote application pour pouvoir continuer a l&apos;utiliser.
        /// </summary>
        internal static string txt_ShouldUpdateVersion {
            get {
                return ResourceManager.GetString("txt_ShouldUpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date début.
        /// </summary>
        internal static string txt_StartDate {
            get {
                return ResourceManager.GetString("txt_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à État.
        /// </summary>
        internal static string txt_Status {
            get {
                return ResourceManager.GetString("txt_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aujourd&apos;hui.
        /// </summary>
        internal static string txt_Today {
            get {
                return ResourceManager.GetString("txt_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Achat par produit.
        /// </summary>
        internal static string txt_TotalAchatsByProduct {
            get {
                return ResourceManager.GetString("txt_TotalAchatsByProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total marges par vendeur.
        /// </summary>
        internal static string txt_TotalMarginBySeler {
            get {
                return ResourceManager.GetString("txt_TotalMarginBySeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total ventes par vendeur.
        /// </summary>
        internal static string txt_TotalSalesBySeler {
            get {
                return ResourceManager.GetString("txt_TotalSalesBySeler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type.
        /// </summary>
        internal static string txt_Types {
            get {
                return ResourceManager.GetString("txt_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type de produit.
        /// </summary>
        internal static string txt_Typesproduct {
            get {
                return ResourceManager.GetString("txt_Typesproduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mettre à jour.
        /// </summary>
        internal static string txt_UpdateVersion {
            get {
                return ResourceManager.GetString("txt_UpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Utilisateur.
        /// </summary>
        internal static string txt_User {
            get {
                return ResourceManager.GetString("txt_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Session.
        /// </summary>
        internal static string txt_UserSession {
            get {
                return ResourceManager.GetString("txt_UserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Traitement ....
        /// </summary>
        internal static string txt_Waiting {
            get {
                return ResourceManager.GetString("txt_Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Semaine.
        /// </summary>
        internal static string txt_Week {
            get {
                return ResourceManager.GetString("txt_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Année.
        /// </summary>
        internal static string txt_Year {
            get {
                return ResourceManager.GetString("txt_Year", resourceCulture);
            }
        }
    }
}
