//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XpertMobileApp {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XpertMobileApp.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string alrt_msg_Cancel {
            get {
                return ResourceManager.GetString("alrt_msg_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion échoué veullez vérifier les informations du serveur.
        /// </summary>
        internal static string alrt_msg_ConnectionError {
            get {
                return ResourceManager.GetString("alrt_msg_ConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion établie avec succes.
        /// </summary>
        internal static string alrt_msg_ConnectionSucces {
            get {
                return ResourceManager.GetString("alrt_msg_ConnectionSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Infos.
        /// </summary>
        internal static string alrt_msg_Info {
            get {
                return ResourceManager.GetString("alrt_msg_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez rensegner les informations du serveur.
        /// </summary>
        internal static string alrt_msg_MissingServerInfos {
            get {
                return ResourceManager.GetString("alrt_msg_MissingServerInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ok.
        /// </summary>
        internal static string alrt_msg_Ok {
            get {
                return ResourceManager.GetString("alrt_msg_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you ant to save the settings.
        /// </summary>
        internal static string alrt_msg_SaveSettings {
            get {
                return ResourceManager.GetString("alrt_msg_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings saved with succes.
        /// </summary>
        internal static string alrt_msg_SettingsSaved {
            get {
                return ResourceManager.GetString("alrt_msg_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        internal static string alrt_msg_title_Settings {
            get {
                return ResourceManager.GetString("alrt_msg_title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connexion.
        /// </summary>
        internal static string lp_btn_Login {
            get {
                return ResourceManager.GetString("lp_btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string lp_btn_Settings {
            get {
                return ResourceManager.GetString("lp_btn_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string lp_lbl_PassWord {
            get {
                return ResourceManager.GetString("lp_lbl_PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        internal static string lp_lbl_UserName {
            get {
                return ResourceManager.GetString("lp_lbl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mot de passe.
        /// </summary>
        internal static string lp_ph_PassWord {
            get {
                return ResourceManager.GetString("lp_ph_PassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom d&apos;utilisateur.
        /// </summary>
        internal static string lp_ph_UserName {
            get {
                return ResourceManager.GetString("lp_ph_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos.
        /// </summary>
        internal static string pn_About {
            get {
                return ResourceManager.GetString("pn_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Analyses.
        /// </summary>
        internal static string pn_Analyses {
            get {
                return ResourceManager.GetString("pn_Analyses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encaissement.
        /// </summary>
        internal static string pn_encaissement {
            get {
                return ResourceManager.GetString("pn_encaissement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accueil.
        /// </summary>
        internal static string pn_home {
            get {
                return ResourceManager.GetString("pn_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enregistrer.
        /// </summary>
        internal static string sp_btn_SaveSettings {
            get {
                return ResourceManager.GetString("sp_btn_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        internal static string sp_btn_settings {
            get {
                return ResourceManager.GetString("sp_btn_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tester la connexion.
        /// </summary>
        internal static string sp_btn_TestConnection {
            get {
                return ResourceManager.GetString("sp_btn_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations de connexion.
        /// </summary>
        internal static string sp_lbl_ConnexionInfos {
            get {
                return ResourceManager.GetString("sp_lbl_ConnexionInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Port.
        /// </summary>
        internal static string sp_lbl_PortNumber {
            get {
                return ResourceManager.GetString("sp_lbl_PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langage.
        /// </summary>
        internal static string sp_lbl_SelectLanguage {
            get {
                return ResourceManager.GetString("sp_lbl_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Serveur.
        /// </summary>
        internal static string sp_lbl_ServerName {
            get {
                return ResourceManager.GetString("sp_lbl_ServerName", resourceCulture);
            }
        }
    }
}
