
using FontAwesome;
using SampleBrowser.SfChart;
using SQLite;
//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Runtime.CompilerServices;
using XpertMobileApp;
using XpertMobileApp.Models;

namespace XpertMobileApp.DAL
{

    public class BASE_CLASS : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;

        public int Index { get; set; }

        [DefaultValue(false)]
        public bool IsSynchronisable { get; set; }

        protected bool SetProperty<T>(ref T backingStore, T value,
        [CallerMemberName] string propertyName = "",
        Action onChanged = null)
        {
            if (EqualityComparer<T>.Default.Equals(backingStore, value))
                return false;

            backingStore = value;
            onChanged?.Invoke();
            OnPropertyChanged(propertyName);
            return true;
        }

        protected void OnPropertyChanged(string propertyName)
        {
            var handler = PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    public partial class TRS_ENCAISS : BASE_CLASS
    {
        [PrimaryKey, AutoIncrement]
        public int ID { get; set; }
        public string CODE_ENCAISS { get; set; } // varchar(32)

        [FieldInfos(VisibleInForm = false, VisibleInFich = true, Designation = "fn_enc_Compte")]
        public DateTime? DATE_ENCAISS { get; set; } // datetime(3)

        // datetime(3)
        [FieldInfos(VisibleInForm = false, VisibleInFich = true, Designation = "fn_enc_Compte")]
        public decimal TOTAL_ENCAISS { get; set; } // money(19,4)

        public string NUM_ENCAISS { get; set; } // varchar(32)
        public string CODE_TIERS { get; set; } // varchar(32)
        public string CODE_MOTIF { get; set; } // varchar(32)
        public string CODE_COMPTE { get; set; } // varchar(32       
        public string CODE_MODE { get; set; } // varchar(1)
        public DateTime? DATE_ECHEANCE { get; set; } // datetime(3)
        //public decimal TOTAL_PAYE { get; set; } // money(19,4) Calculé dans la vue
        public string CODE_TYPE { get; set; } // varchar(4)
        public string REF_REG { get; set; } // varchar(200)
        [FieldInfos(VisibleInForm = false, VisibleInFich = true, Designation = "PEncDec_Note_Enc")]
        public string NOTE_ENC { get; set; } // text(2147483647)
        public string CODE_VIR { get; set; } // varchar(32)
        public int SENS_DOC { get; set; } // smallint(5)
        public DateTime? CREATED_ON { get; set; } // datetime(3)
        public string CREATED_BY { get; set; } // varchar(200)
        public DateTime? MODIFIED_ON { get; set; } // datetime(3)
        public string MODIFIED_BY { get; set; } // varchar(200)
        public string ID_CAISSE { get; set; } // varchar(50)
        public string EXERCICE { get; set; } // char(4)
        public bool BY_PARENT { get; set; } // bit
        public bool AUTO_DISPATSH { get; set; } // bit
        public decimal MT_RECU { get; set; } // money(19,4)
        public bool MONTANT_SUM { get; set; } // 
        public DateTime? DATE_VALEUR { get; set; }
        public bool ANNULEE { get; set; }
        private string cODE_DOC;
        public string CODE_DOC { get => cODE_DOC; set => cODE_DOC = value; }
        private string CODE_TOURNEE_DETAIL;
        public string cODE_TOURNEE_DETAIL
        {
            get
            {
                return CODE_TOURNEE_DETAIL;
            }
            set
            {
                CODE_TOURNEE_DETAIL = value;
            }
        }
    }

    // View
    public partial class View_TRS_ENCAISS : TRS_ENCAISS
    {
        [FieldInfos(VisibleInForm = false, VisibleInFich = true, Designation = "fn_enc_Compte")]
        public string NOM_TIERS { get; set; } // varchar(501)
        [FieldInfos(VisibleInForm = false, VisibleInFich = true, Designation = "fn_enc_Compte")]
        public string DESIGN_COMPTE { get; set; } // varchar(100)
        [FieldInfos(VisibleInForm = false, VisibleInFich = true, Designation = "fn_enc_Compte")]
        public string DESIGN_MOTIF { get; set; } // varchar(300)
        [FieldInfos(VisibleInForm = false, VisibleInFich = true, Designation = "PEncDec_Design_Mode")]
        public string DESIGN_MODE { get; set; } // varchar(300)
        public string DESIGNATION_TYPE { get; set; } // varchar(200)
        public decimal TOTAL_PAYE { get; set; } // money(19,4)
        public string TYPE_TIERS { get; set; } // varchar(5)
        public string ADRESSE_TIERS { get; set; } // varchar(500)
        public string NUM_ASSURE { get; set; } // varchar(12)
        public decimal TOTAL_ENCAISS_REAL { get; set; } // money(19,4)
        public decimal TOTAL_RESTE { get; set; } // money(19,4)
        public decimal TOTAL_RESTE_REAL { get; set; } // money(19,4)
        public string TYPE_COMPTE { get; set; } // varchar(4)    
        public decimal ANCIEN_SOLDE { get; set; } // money(19,4)
        public decimal NOUVEAU_SOLDE { get; set; } // money(19,4)
        public bool IS_VALORISEE { get; set; }
        public DateTime? DATE_VALEUR_VIEW { get; set; }
        public bool IS_CLOTURABLE { get; set; }
        public string CODE_COMPTE_TYPE { get; set; }
        public string DESIGNATION_TYPE_COMPTE { get; set; }
        public string CODE_FAMILLE_TIERS { get; set; }
        public double GPS_LATITUDE { get; set; }
        public double GPS_LONGITUDE { get; set; }
        public override string ToString()
        {
            return AppResources.pn_encaissement + " N° : " + NUM_ENCAISS;
        }

        public Color ValColor
        {
            get
            {
                return CODE_TYPE == "ENC" ? Color.Black : Color.Red;
            }
        }

        public string ValIcon
        {
            get
            {
                return CODE_TYPE == "ENC" ? FontAwesomeIcons.Arrow_Up : FontAwesomeIcons.Arrow_Down;
            }
        }
        public string CODE_TOURNEE { get; set; }
        private bool is_synchronisable { get; set; } = true;
        public bool IS_SYNCHRONISABLE
        {
            get
            {
                    return is_synchronisable;
            }
            set
            {
                is_synchronisable = value;
            }
        }
    }

    public class SESSION_INFO : BASE_CLASS
    {
        public DateTime DATE_JOURNEE { get; set; } // datetime(3)
        public string POSTE_DEBUT { get; set; } // nvarchar(250)
        public decimal MONT_DEPART { get; set; } // money(19,4)
        public decimal MONT_CLOTURE_PH { get; set; } // money(19,4)
        public bool TRANS_MONTANT { get; set; } // bit
        public string POSTE_CLOTURE { get; set; } // nvarchar(250)
    }
    public partial class TRS_JOURNEES : SESSION_INFO
    {
        public override string ToString()
        {
            return string.Format("{0} ({1})", DEBUTEE_PAR, POSTE_DEBUT);
        }
        [PrimaryKey, AutoIncrement]
        public int ID { get; set; }
        public string ID_CAISSE { get; set; } // varchar(50)
        public string CODE_COMPTE { get; set; } // varchar(20)

        public string DESIGN_COMPTE { get; set; } // varchar(20)

        public string USER_SESSION { get; set; } // varchar(20)

        public DateTime? DATE_DEBUT { get; set; } // datetime(3)
        public string DEBUTEE_PAR { get; set; } // varchar(100)

        public decimal MONT_VENTE { get; set; } // money(19,4)
        public decimal MONT_CREDIT { get; set; } // money(19,4)
        public decimal MONT_CREDIT_PHARM { get; set; } // money(19,4)
        public decimal MONT_CREDIT_CHIFA { get; set; } // money(19,4)
        public decimal MONT_PAIEMENT_CREDIT { get; set; } // money(19,4)
        public decimal MONT_ENCAISSEMENT { get; set; } // money(19,4)
        public decimal MONT_DECAISSEMENT { get; set; } // money(19,4)
        public decimal MONT_REG_FOURNISSEUR { get; set; } // money(19,4)
        public decimal MONT_REG_CLIENT { get; set; } // money(19,4)
        public decimal MONT_CLOTURE_TH { get; set; } // money(19,4)

        public decimal MONT_CLOTURE_TH_ARRODI { get; set; } // money(19,4)
        public decimal MONT_CLOTURE_PH_ESPECE { get; set; } // money(19,4)
        public decimal MONT_CLOTURE_PH_TPE { get; set; } // money(19,4)

        public decimal MONT_CLOTURE_PH_virtual
        {
            get
            {
                if (MONT_CLOTURE_PH == 0)
                {
                    return MONT_CLOTURE_PH_ESPECE + MONT_CLOTURE_PH_TPE;
                }
                else
                {
                    return MONT_CLOTURE_PH;
                }
            }
        }


        public decimal MONT_ECART { get; set; } // money(19,4)
        public decimal MONT_CREDIT_CASNOS { get; set; } // money(19,4)
        public decimal TR_PHARM_PAYE { get; set; } // money(19,4)
        public decimal TR_PHARM_CREDIT { get; set; } // money(19,4)
        public decimal TR_CHIFA_PAYE { get; set; } // money(19,4)        
        public decimal TR_CHIFA_CREDIT { get; set; } // money(19,4)
        public decimal TR_CASNOS_PAYE { get; set; } // money(19,4)
        public decimal TR_CASNOS_CREDIT { get; set; } // money(19,4)
        public decimal MONT_RETOUR { get; set; } // money(19,4)
        public decimal MONT_REMBOURSE { get; set; } // money(19,4)
        public DateTime? DATE_CLOTURE { get; set; } // datetime(3)
        public string CLOTUREE_PAR { get; set; } // varchar(100)

        public bool JOURNEE_CLOTUREE { get; set; } // bit

        public string TRANS_COMPTE { get; set; } // varchar(200)
        public string EXERCICE { get; set; } // char(4)
        public DateTime? MODIFIED_ON { get; set; } // datetime(3)
        public string MODIFIED_BY { get; set; } // varchar(200)  
        public DateTime? CREATED_ON { get; set; } // datetime(3)
        public string CREATED_BY { get; set; } // varchar(200) 

        private decimal GetPercent(decimal val, decimal total)
        {
            if (total == 0) return 0;

            return (val * 100) / total;
        }

        public List<ChartDataModel> Data1
        {
            get
            {
                decimal total = MONT_ENCAISSEMENT + MONT_VENTE + MONT_PAIEMENT_CREDIT + TR_CHIFA_PAYE + TR_CASNOS_PAYE + MONT_DECAISSEMENT + MONT_RETOUR + MONT_REMBOURSE;

                var data = new List<ChartDataModel>();
                data.Add(new ChartDataModel("Enc.Libre", Convert.ToDouble(GetPercent(MONT_ENCAISSEMENT, total))));
                data.Add(new ChartDataModel("Ventes Cash", Convert.ToDouble(GetPercent(MONT_VENTE, total))));
                data.Add(new ChartDataModel("Paiement crédit", Convert.ToDouble(GetPercent(MONT_PAIEMENT_CREDIT, total))));
                data.Add(new ChartDataModel("Tarif CHIFA", Convert.ToDouble(GetPercent(TR_CHIFA_PAYE, total))));
                data.Add(new ChartDataModel("Tarif Pharmnos", Convert.ToDouble(GetPercent(TR_CASNOS_PAYE, total))));

                data.Add(new ChartDataModel("Déc.libre", Convert.ToDouble(GetPercent(MONT_DECAISSEMENT, total))));
                data.Add(new ChartDataModel("Retour", Convert.ToDouble(GetPercent(MONT_RETOUR, total))));
                data.Add(new ChartDataModel("Remboursement", Convert.ToDouble(GetPercent(MONT_REMBOURSE, total))));
                // Total vente CVM(militaire) si le module CVM activé.
                return data;
            }
        }

        public List<ChartDataModel> Data2
        {
            get
            {
                decimal total = MONT_CREDIT + TR_CHIFA_CREDIT + TR_PHARM_CREDIT + MONT_CREDIT_CHIFA + MONT_CREDIT_PHARM;

                var data = new List<ChartDataModel>();
                data.Add(new ChartDataModel("Ventes libre", Convert.ToDouble(GetPercent(MONT_CREDIT, total))));
                data.Add(new ChartDataModel("Tarif CHIFA", Convert.ToDouble(GetPercent(TR_CHIFA_CREDIT, total))));
                data.Add(new ChartDataModel("Tarif Pharmnos", Convert.ToDouble(GetPercent(TR_PHARM_CREDIT, total))));
                data.Add(new ChartDataModel("Crédit CHIFA", Convert.ToDouble(GetPercent(MONT_CREDIT_CHIFA, total))));
                data.Add(new ChartDataModel("Crédit Pharmnos", Convert.ToDouble(GetPercent(MONT_CREDIT_PHARM, total))));
                return data;
                // Total vente CVM(militaire) si le module CVM activé.
            }
        }
    }

    public partial class BSE_COMPTE
    {
        public string CODE_COMPTE { get; set; } // varchar(21)
        public string DESIGN_COMPTE { get; set; } // varchar(100)
        public string CODE_TYPE { get; set; } // varchar(4)
        public string AGENCE_COMPTE { get; set; } // varchar(200)
        public string RIB_COMPTE { get; set; } // varchar(200)
    }

    public partial class View_BSE_COMPTE : BSE_COMPTE
    {
        public decimal SOLDE_COMPTE { get; set; }
        public decimal SOLDE_COMPTE_TH { get; set; }
        public string DESIGNATION_TYPE { get; set; } // varchar(200)
        public bool IS_CLOTURABLE { get; set; }
        public string MODE_REG { get; set; }
        public int TYPE_COMPTE { get; set; }
        public string CODE_GROUPE { get; set; }
    }

    public partial class TRS_TIERS : BASE_CLASS
    {
        [PrimaryKey, AutoIncrement]
        public int ID { get; set; }
        public string CODE_TIERS { get; set; } // varchar(32)
        public string NUM_TIERS { get; set; } // varchar(32)
        public string CODE_FAMILLE { get; set; } // varchar(10)
        public string CODE_TYPE { get; set; } // varchar(5)
        public string NOM_TIERS { get; set; } // varchar(250)
        public string PRENOM_TIERS { get; set; } // varchar(250)
        public string GERANT { get; set; } // varchar(200)
        public string ADRESSE_TIERS { get; set; } // varchar(500)
        public string TEL1_TIERS { get; set; } // varchar(50)
        public string TEL2_TIERS { get; set; } // varchar(50)
        public string FAX_TIERS { get; set; } // varchar(50)
        public string RC_TIERS { get; set; } // varchar(50)
        public string MF_TIERS { get; set; } // varchar(20)
        public string AI_TIERS { get; set; } // varchar(20)
        public string COMPTE_TIERS { get; set; } // varchar(60)
        public string NUM_ASSURE { get; set; } // varchar(12)
        public short ACTIF_TIERS { get; set; } // tinyint(3)
        public decimal SEUIL_CREDIT { get; set; } // money(19,4)
        public string RANG_AD { get; set; } // char(2)
        public short NBR_JOUR_ALERTE_CREDIT { get; set; } // smallint(5)
        public DateTime? DATE_NAISSANCE { get; set; } // datetime(3)
        public string GROUPE_SANGUIN { get; set; } // varchar(10)
        public DateTime? DATE_GROUPAGE { get; set; } // datetime(3)
        public int? TYPE_PRIX_VENTE { get; set; }
        public string RANG_CASNOS { get; set; } // char(2)
        public string NUM_CARTE_IDENT { get; set; }
        public DateTime? DATE_CART_IDENT { get; set; }
        public string WILAYA_CARTE_ID { get; set; }
        public bool EXON_TIMBRE { get; set; }
        public bool EXON_TVA { get; set; }
        public string CODE_GROUPE { get; set; }
        public DateTime? CREATED_ON { get; set; }
        public string CREATED_BY { get; set; }
        public string MACHINE_NAME_CREATED { get; set; }
        public DateTime? MODIFIED_ON { get; set; }
        public string MODIFIED_BY { get; set; }
        public string MACHINE_NAME_MODIFIED { get; set; }
        public string APP_NAME { get; set; }
        public string APP_VERSION { get; set; }
        public decimal TOTAL_CREDIT { get; set; } // money(19,4)
        public decimal TOTAL_PAIEMENT { get; set; } // money(19,4)
        public decimal RESTE_CREDIT { get; set; } // money(19,4)
        public decimal RESTE_PAIEMENT { get; set; } // money(19,4)       
        // public decimal SOLDE { get; set; } // money(19,4)    Ancienne colonne
        public bool INCLUDE_UG { get; set; }
        public bool PPA_BY_PRIXVENTE { get; set; }


        // information pour Malade CVM
        public string SEXE { get; set; } // tinyint(3)
        public string LP { get; set; }//varchar(10) 
        public byte CODE_SIT_FAM { get; set; } // tinyint(3)
        public string CODE_TYPE_CONTRAT { get; set; } // tinyint(3)
        public string NUM_CCP { get; set; } // varchar(20)
        public DateTime? DATE_FIN_CONTRAT { get; set; } // datetime(3)
        public string OBS { get; set; } // nvarchar(250)
        public string NUM_KAFALA_AY_DROIT { get; set; }//varchar(50)
        public string ID_CVM_CENTRE { get; set; }//
        public string AGE { get; set; }//
        public string EMAIL { get; set; }
        public string CODE_LIEUX { get; set; }
        public double GPS_LATITUDE { get; set; }
        public double GPS_LONGITUDE { get; set; }
        public string MODE_CAL_MT_ECHANGE { get; set; }
    }

    public partial class View_TRS_TIERS : TRS_TIERS
    {
        [Ignore]
        public string FULL_NOM_TIERS
        {
            get
            {
                return (string.IsNullOrEmpty(NOM_TIERS) ? "" : NOM_TIERS) + (string.IsNullOrEmpty(PRENOM_TIERS) ? "" : PRENOM_TIERS);
            }
        } // varchar(501)
        public string NOM_TIERS1 { get; set; } // varchar(501)
        public string DESIGN_FAMILLE { get; set; } // varchar(50)
        public string DESIGNATION_TYPE { get; set; } // varchar(200)
        public decimal SOLDE_TIERS { get; set; } // money(19,4)        

        public string SOLDE_TIERS_TXT { get; set; } // money(19,4)         
        public string NUM_CARTE_FIDELITE { get; set; } // varchar(20)
        public string CODE_CARTE_FIDELITE { get; set; } // varchar(20)
        public decimal TOTAL_POINT_FIDELITE { get; set; } // varchar(20)
        public string DESIGNATION_MODE_CAL { get; set; } // string 
        public short STATUT_TIERS { get; set; } // 
        public DateTime? LAST_CREANCE { get; set; } // datetime(3)
        public DateTime? LAST_ENCAISS { get; set; } // datetime(3)
        public string DESIGNATION_LP
        {
            get
            {
                string DLP = string.Empty;
                if (LP != null)
                {
                    switch (this.LP.Trim())
                    {
                        case "E":
                            DLP = "Enfant";
                            break;
                        case "AS":
                            DLP = "Assuré";
                            break;
                        case "C":
                            DLP = "Conjoint";
                            break;
                        case "ASC":
                            DLP = "Ascendant";
                            break;
                    }
                }
                return DLP;
            }
        }
        public STAT_TIERS_MOBILE ETAT_TIERS { get; set; }
    }
    public enum STAT_TIERS_MOBILE
    {
        UNTOUCHED,
        ADDED,
        UPDATED
    }

    public partial class View_TRS_TIERS_ACTIVITY
    {
        public string CODE_TIERS { get; set; } // varchar(20)
        public string TYPE_DOC { get; set; } // varchar(20)
        public decimal TOTAL_PAYE { get; set; } // varchar(20)
        public string CODE_DOC { get; set; } // varchar(20)
        public DateTime? DATE_DOC { get; set; }
    }

    public partial class BSE_ENCAISS_MOTIFS
    {
        public string CODE_MOTIF { get; set; } // varchar(20)
        public string DESIGN_MOTIF { get; set; } // varchar(300)
        public string TYPE_MOTIF { get; set; } // varchar(3)
        public bool IS_SYSTEM { get; set; } // varchar(3)
    }

    public partial class BSE_TIERS_FAMILLE
    {
        [PrimaryKey, AutoIncrement]
        public int ID { get; set; }
        public string CODE_FAMILLE { get; set; } // varchar(10)
        public string DESIGN_FAMILLE { get; set; } // varchar(50)
        public string CODE_TYPE { get; set; } // varchar(4)
        public short STATUT { get; set; }
    }

    public partial class View_BSE_TIERS_FAMILLE : BSE_TIERS_FAMILLE
    {
        public string DESIGNATION_TYPE { get; set; } // varchar(200)
    }

    public class BSE_TABLE_TYPE
    {
        [PrimaryKey, AutoIncrement]
        public int ID { get; set; }
        public string CODE_TYPE { get; set; }
        public string DESIGNATION_TYPE { get; set; }
    }


    public class TRS_VIREMENT : BASE_CLASS
    {
        public string ID_CAISSE { get; set; } // varchar(32)
        public string CODE_VIR { get; set; } // varchar(32)
        public string CODE_ENCAISS { get; set; } // varchar(32)
        public DateTime? DATE_ECHEANCE { get; set; } // datetime(3)
        public string CODE_DECAISS { get; set; } // varchar(32)
        public string CODE_COMPTE_SRC { get; set; } // varchar(32)
        public string CODE_COMPTE_DEST { get; set; } // varchar(32)
        public string CODE_MOTIF { get; set; } // varchar(32)
        public DateTime? DATE_ENCAISS { get; set; } // datetime(3)
        public string CODE_MODE { get; set; } // varchar(1)
        public string REF_REG { get; set; } // varchar(200)
        public decimal TOTAL_ENCAISS { get; set; } // money(19,4)

        public string NOTE_ENC { get; set; } // text(2147483647)
        public string DESIGN_MOTIF { get; set; } // varchar(300)
        public string DESIGN_COMPTE_DEST { get; set; } // varchar(100)
        public string DESIGN_COMPTE_SRC { get; set; } // varchar(100)
        public string DESIGN_MODE { get; set; } // varchar(300)
        public DateTime? MODIFIED_ON { get; set; } // datetime(3)
        public string MODIFIED_BY { get; set; } // varchar(200)  
        public DateTime? CREATED_ON { get; set; } // datetime(3)
        public string CREATED_BY { get; set; } // varchar(200)        

    }

    //View TRS Virement
    public class View_TRS_VIREMENT : TRS_VIREMENT
    {
    }


    public partial class BSE_MODE_REG : BASE_CLASS
    {
        public string CODE_MODE { get; set; } // varchar(1)
        public string DESIGN_MODE { get; set; } // varchar(300)
        public bool ECH_MODE { get; set; } // bit
    }
    public partial class TRS_CREDIT_PAIEMENT : BASE_CLASS
    {

    }
    public partial class View_TRS_CREDIT_PAIEMENT : TRS_CREDIT_PAIEMENT
    {
        public string CODE_DOCUMENT { get; set; } // varchar(532)
        public int ORDER_DOCUMENT { get; set; } // int(10)
        public string DESIGN_DOCUMENT { get; set; } // varchar(532)
        public string CODE_TIERS { get; set; } // varchar(32)
        public string NOM_TIERS { get; set; } // varchar(501)
        public string NUM_DOCUMENT { get; set; } // varchar(32)
        public DateTime? DATE_DOCUMENT { get; set; } // datetime(3)
        public string TYPE_DOCUMENT { get; set; } // varchar(4)
        public string TYPE_DOC { get; set; } // varchar(4)
        public string OBERSVATION { get; set; } // text(2147483647)
        public string CREATED_BY { get; set; } // varchar(200)
        public decimal TOTAL_CREDIT { get; set; } // money(19,4)
        public decimal TOTAL_CREDIT_REAL { get; set; } // money(19,4)
        public decimal RESTE_CREDIT { get; set; } // money(19,4)
        public decimal RESTE_CREDIT_REAL { get; set; } // money(19,4)
        public decimal TOTAL_PAIEMENT_REAL { get; set; } // money(19,4)
        public decimal TOTAL_PAIEMENT { get; set; } // money(19,4)
        public decimal RESTE_PAIEMENT { get; set; } // money(19,4)
        public decimal RESTE_PAIEMENT_REAL { get; set; } // money(19,4) 
        public string CATEGORY_DOCUMENT { get; set; } // varchar(32)
        public string REF_TIERS { get; set; } // varchar(32)
        public string NUM_ASSURE { get; set; } // varchar(32)
        public string TYPE_TIERS { get; set; } // varchar(5)
        public string FAMILLE_TIERS { get; set; } // varchar
        public DateTime? CREATED_ON { get; set; } // datetime(3)        

    }


}