
using SQLite;
//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by BLToolkit template for T4.
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;

namespace Xpert.Pharm.DAL
{

    public partial class TRS_ENCAISS
    {
        [PrimaryKey()]
        public string CODE_ENCAISS { get; set; } // varchar(32)
        public string NUM_ENCAISS { get; set; } // varchar(32)
        public string CODE_TIERS { get; set; } // varchar(32)
        public string CODE_MOTIF { get; set; } // varchar(32)
        public string CODE_COMPTE { get; set; } // varchar(32)
        public DateTime? DATE_ENCAISS { get; set; } // datetime(3)
        public string CODE_MODE { get; set; } // varchar(1)
        public DateTime? DATE_ECHEANCE { get; set; } // datetime(3)
        public decimal TOTAL_ENCAISS { get; set; } // money(19,4)
        //public decimal TOTAL_PAYE { get; set; } // money(19,4) Calculé dans la vue
        public string CODE_TYPE { get; set; } // varchar(4)
        public string REF_REG { get; set; } // varchar(200)
        public string NOTE_ENC { get; set; } // text(2147483647)
        public string CODE_VIR { get; set; } // varchar(32)
        public int SENS_DOC { get; set; } // smallint(5)
        public DateTime? CREATED_ON { get; set; } // datetime(3)
        public string CREATED_BY { get; set; } // varchar(200)
        public DateTime? MODIFIED_ON { get; set; } // datetime(3)
        public string MODIFIED_BY { get; set; } // varchar(200)
        public string ID_CAISSE { get; set; } // varchar(50)
        public string EXERCICE { get; set; } // char(4)
        public bool BY_PARENT { get; set; } // bit
        public bool AUTO_DISPATSH { get; set; } // bit
        public decimal MT_RECU { get; set; } // money(19,4)
        public bool MONTANT_SUM { get; set; } // 
        public DateTime? DATE_VALEUR { get; set; }
        public bool ANNULEE { get; set; }

    }

    // View
    public partial class View_TRS_ENCAISS : TRS_ENCAISS
    {
        public string DESIGNATION_TYPE { get; set; } // varchar(200)
        public decimal TOTAL_PAYE { get; set; } // money(19,4)
        public string NOM_TIERS { get; set; } // varchar(501)
        public string DESIGN_COMPTE { get; set; } // varchar(100)
        public string TYPE_TIERS { get; set; } // varchar(5)
        public string ADRESSE_TIERS { get; set; } // varchar(500)
        public string NUM_ASSURE { get; set; } // varchar(12)
        public string DESIGN_MODE { get; set; } // varchar(300)
        public string DESIGN_MOTIF { get; set; } // varchar(300)
        public decimal TOTAL_ENCAISS_REAL { get; set; } // money(19,4)
        public decimal TOTAL_RESTE { get; set; } // money(19,4)
        public decimal TOTAL_RESTE_REAL { get; set; } // money(19,4)
        public string TYPE_COMPTE { get; set; } // varchar(4)    
        public decimal ANCIEN_SOLDE { get; set; } // money(19,4)
        public decimal NOUVEAU_SOLDE { get; set; } // money(19,4)
        public bool IS_VALORISEE { get; set; }
        public DateTime? DATE_VALEUR_VIEW { get; set; }
        public bool IS_CLOTURABLE { get; set; }
        public string CODE_COMPTE_TYPE { get; set; }
        public string DESIGNATION_TYPE_COMPTE { get; set; }
        public string CODE_FAMILLE_TIERS { get; set; }
    }

    public partial class TRS_JOURNEES
    {
        [PrimaryKey()]
        public string ID_CAISSE { get; set; } // varchar(50)
        public string CODE_COMPTE { get; set; } // varchar(20)

        public string DESIGN_COMPTE { get; set; } // varchar(20)

        public string USER_SESSION { get; set; } // varchar(20)
        public DateTime? DATE_JOURNEE { get; set; } // datetime(3)
        public DateTime? DATE_DEBUT { get; set; } // datetime(3)
        public string DEBUTEE_PAR { get; set; } // varchar(100)
        public string POSTE_DEBUT { get; set; } // nvarchar(250)
        public decimal MONT_DEPART { get; set; } // money(19,4)
        public decimal MONT_VENTE { get; set; } // money(19,4)
        public decimal MONT_CREDIT { get; set; } // money(19,4)
        public decimal MONT_CREDIT_PHARM { get; set; } // money(19,4)
        public decimal MONT_CREDIT_CHIFA { get; set; } // money(19,4)
        public decimal MONT_PAIEMENT_CREDIT { get; set; } // money(19,4)
        public decimal MONT_ENCAISSEMENT { get; set; } // money(19,4)
        public decimal MONT_DECAISSEMENT { get; set; } // money(19,4)
        public decimal MONT_REG_FOURNISSEUR { get; set; } // money(19,4)
        public decimal MONT_REG_CLIENT { get; set; } // money(19,4)
        public decimal MONT_CLOTURE_TH { get; set; } // money(19,4)
        public decimal MONT_CLOTURE_PH { get; set; } // money(19,4)
        public decimal MONT_CLOTURE_TH_ARRODI { get; set; } // money(19,4)
        public decimal MONT_ECART { get; set; } // money(19,4)
        public decimal MONT_CREDIT_CASNOS { get; set; } // money(19,4)
        public decimal TR_PHARM_PAYE { get; set; } // money(19,4)
        public decimal TR_PHARM_CREDIT { get; set; } // money(19,4)
        public decimal TR_CHIFA_PAYE { get; set; } // money(19,4)        
        public decimal TR_CHIFA_CREDIT { get; set; } // money(19,4)
        public decimal TR_CASNOS_PAYE { get; set; } // money(19,4)
        public decimal TR_CASNOS_CREDIT { get; set; } // money(19,4)
        public decimal MONT_RETOUR { get; set; } // money(19,4)
        public decimal MONT_REMBOURSE { get; set; } // money(19,4)
        public DateTime? DATE_CLOTURE { get; set; } // datetime(3)
        public string CLOTUREE_PAR { get; set; } // varchar(100)
        public string POSTE_CLOTURE { get; set; } // nvarchar(250)
        public bool JOURNEE_CLOTUREE { get; set; } // bit
        public bool TRANS_MONTANT { get; set; } // bit
        public string TRANS_COMPTE { get; set; } // varchar(200)
        public string EXERCICE { get; set; } // char(4)
        public DateTime? MODIFIED_ON { get; set; } // datetime(3)
        public string MODIFIED_BY { get; set; } // varchar(200)  
        public DateTime? CREATED_ON { get; set; } // datetime(3)
        public string CREATED_BY { get; set; } // varchar(200)      
    }

    public partial class BSE_COMPTE
    {
        public string CODE_COMPTE { get; set; } // varchar(21)
        public string DESIGN_COMPTE { get; set; } // varchar(100)
        public string CODE_TYPE { get; set; } // varchar(4)
        public string AGENCE_COMPTE { get; set; } // varchar(200)
        public string RIB_COMPTE { get; set; } // varchar(200)
    }

    public partial class View_BSE_COMPTE : BSE_COMPTE
    {
        public decimal SOLDE_COMPTE { get; set; }
        public decimal SOLDE_COMPTE_TH { get; set; }
        public string DESIGNATION_TYPE { get; set; } // varchar(200)
        public bool IS_CLOTURABLE { get; set; }
        public string MODE_REG { get; set; }
        public int TYPE_COMPTE { get; set; }
        public string CODE_GROUPE { get; set; }
    }
}
